/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './pages/__root'
import { Route as authLayoutImport } from './pages/(auth)/_layout'
import { Route as appLayoutImport } from './pages/(app)/_layout'
import { Route as authLayoutEntryIndexImport } from './pages/(auth)/_layout/entry/index'
import { Route as appLayoutLikedCatsIndexImport } from './pages/(app)/_layout/liked-cats/index'
import { Route as appLayoutAllCatsIndexImport } from './pages/(app)/_layout/_all-cats/index'

// Create Virtual Routes

const authImport = createFileRoute('/(auth)')()
const appImport = createFileRoute('/(app)')()

// Create/Update Routes

const authRoute = authImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const appRoute = appImport.update({
  id: '/(app)',
  getParentRoute: () => rootRoute,
} as any)

const authLayoutRoute = authLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => authRoute,
} as any)

const appLayoutRoute = appLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => appRoute,
} as any)

const authLayoutEntryIndexRoute = authLayoutEntryIndexImport.update({
  path: '/entry/',
  getParentRoute: () => authLayoutRoute,
} as any)

const appLayoutLikedCatsIndexRoute = appLayoutLikedCatsIndexImport.update({
  path: '/liked-cats/',
  getParentRoute: () => appLayoutRoute,
} as any)

const appLayoutAllCatsIndexRoute = appLayoutAllCatsIndexImport.update({
  path: '/',
  getParentRoute: () => appLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appImport
      parentRoute: typeof rootRoute
    }
    '/(app)/_layout': {
      id: '/_layout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appLayoutImport
      parentRoute: typeof appRoute
    }
    '/(auth)': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/_layout': {
      id: '/_layout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authLayoutImport
      parentRoute: typeof authRoute
    }
    '/(app)/_layout/_all-cats/': {
      id: '/_layout/_all-cats/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appLayoutAllCatsIndexImport
      parentRoute: typeof appLayoutImport
    }
    '/(app)/_layout/liked-cats/': {
      id: '/_layout/liked-cats/'
      path: '/liked-cats'
      fullPath: '/liked-cats'
      preLoaderRoute: typeof appLayoutLikedCatsIndexImport
      parentRoute: typeof appLayoutImport
    }
    '/(auth)/_layout/entry/': {
      id: '/_layout/entry/'
      path: '/entry'
      fullPath: '/entry'
      preLoaderRoute: typeof authLayoutEntryIndexImport
      parentRoute: typeof authLayoutImport
    }
  }
}

// Create and export the route tree

interface appLayoutRouteChildren {
  appLayoutAllCatsIndexRoute: typeof appLayoutAllCatsIndexRoute
  appLayoutLikedCatsIndexRoute: typeof appLayoutLikedCatsIndexRoute
}

const appLayoutRouteChildren: appLayoutRouteChildren = {
  appLayoutAllCatsIndexRoute: appLayoutAllCatsIndexRoute,
  appLayoutLikedCatsIndexRoute: appLayoutLikedCatsIndexRoute,
}

const appLayoutRouteWithChildren = appLayoutRoute._addFileChildren(
  appLayoutRouteChildren,
)

interface appRouteChildren {
  appLayoutRoute: typeof appLayoutRouteWithChildren
}

const appRouteChildren: appRouteChildren = {
  appLayoutRoute: appLayoutRouteWithChildren,
}

const appRouteWithChildren = appRoute._addFileChildren(appRouteChildren)

interface authLayoutRouteChildren {
  authLayoutEntryIndexRoute: typeof authLayoutEntryIndexRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authLayoutEntryIndexRoute: authLayoutEntryIndexRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface authRouteChildren {
  authLayoutRoute: typeof authLayoutRouteWithChildren
}

const authRouteChildren: authRouteChildren = {
  authLayoutRoute: authLayoutRouteWithChildren,
}

const authRouteWithChildren = authRoute._addFileChildren(authRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof appLayoutAllCatsIndexRoute
  '/liked-cats': typeof appLayoutLikedCatsIndexRoute
  '/entry': typeof authLayoutEntryIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof appLayoutAllCatsIndexRoute
  '/liked-cats': typeof appLayoutLikedCatsIndexRoute
  '/entry': typeof authLayoutEntryIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof authRouteWithChildren
  '/_layout': typeof authLayoutRouteWithChildren
  '/_layout/_all-cats/': typeof appLayoutAllCatsIndexRoute
  '/_layout/liked-cats/': typeof appLayoutLikedCatsIndexRoute
  '/_layout/entry/': typeof authLayoutEntryIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/liked-cats' | '/entry'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/liked-cats' | '/entry'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/_layout/_all-cats/'
    | '/_layout/liked-cats/'
    | '/_layout/entry/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  appRoute: typeof appRouteWithChildren
  authRoute: typeof authRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  appRoute: appRouteWithChildren,
  authRoute: authRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/"
      ]
    },
    "/": {
      "filePath": "(auth)",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "(auth)/_layout.tsx",
      "parent": "/",
      "children": [
        "/_layout/entry/"
      ]
    },
    "/_layout/_all-cats/": {
      "filePath": "(app)/_layout/_all-cats/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/liked-cats/": {
      "filePath": "(app)/_layout/liked-cats/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/entry/": {
      "filePath": "(auth)/_layout/entry/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
